version: "2"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    expose:
      - "8081"
    ports:
      - "8081:8081"
      - "8100:8100"
    
